// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoPhYEzJApo_ofHefQK4eeWJ_zbjn-Ra4',
    appId: '1:729475404811:web:a13695b596a50b03b8630e',
    messagingSenderId: '729475404811',
    projectId: 'helloworld-ee262',
    authDomain: 'helloworld-ee262.firebaseapp.com',
    storageBucket: 'helloworld-ee262.firebasestorage.app',
    measurementId: 'G-MXE96G973W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlybVhIUTGx6Rvt9xQIgb1SrGyFcWvp-0',
    appId: '1:729475404811:android:685cfbcae9b9b741b8630e',
    messagingSenderId: '729475404811',
    projectId: 'helloworld-ee262',
    storageBucket: 'helloworld-ee262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJT73ojX2NP2ZhV-oZm8OIhudHJoq_Q34',
    appId: '1:729475404811:ios:e5af124838485cb1b8630e',
    messagingSenderId: '729475404811',
    projectId: 'helloworld-ee262',
    storageBucket: 'helloworld-ee262.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJT73ojX2NP2ZhV-oZm8OIhudHJoq_Q34',
    appId: '1:729475404811:ios:e5af124838485cb1b8630e',
    messagingSenderId: '729475404811',
    projectId: 'helloworld-ee262',
    storageBucket: 'helloworld-ee262.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoPhYEzJApo_ofHefQK4eeWJ_zbjn-Ra4',
    appId: '1:729475404811:web:10699cad7d11d3b2b8630e',
    messagingSenderId: '729475404811',
    projectId: 'helloworld-ee262',
    authDomain: 'helloworld-ee262.firebaseapp.com',
    storageBucket: 'helloworld-ee262.firebasestorage.app',
    measurementId: 'G-HCQXXVW990',
  );

}